website/__init__.py
from flask import Flask, request, session
from flask_babelex import Babel


def create_app():
    app = Flask(__name__)
    #app.config['BABEL_DEFAULT_LOCALE'] = 'en'
    app.config['LANGUAGES'] = { 'en' : 'English', 'hr': 'Hrvatski'}
    app.secret_key = "wineata super secret key"
    babel = Babel(app)
    
    @app.context_processor
    def inject_conf_var():
        return dict(AVAILABLE_LANGUAGES=app.config['LANGUAGES'], CURRENT_LANGUAGE=session.get('lang', request.accept_languages.best_match(app.config['LANGUAGES'].keys())))
    
    @babel.localeselector
    def get_locale():
        if request.args.get('lang'):
            session['lang'] = request.args.get('lang')
        return session.get('lang', request.accept_languages.best_match(app.config['LANGUAGES'].keys()))

    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    return app

website/auth.py
from flask import Blueprint, redirect, render_template, request, url_for

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['POST', 'GET'])
def login():
    return render_template('login.html')

@auth.route('/register', methods=['POST', 'GET'])
def register():
    return render_template('register.html')

website/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for

views = Blueprint('views', __name__)

@views.route('/')
def index():
    return render_template('index.html')

@views.route('/wineata')
def wineata():
    return render_template('wineata.html')

@views.route('/wineries')
def wineries():
    return render_template('wineries.html')

@views.route('/lang=<language>')
def set_language(language=None):
    session['lang'] = language
    return redirect(request.referrer)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='icons/wine.ico') }}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container-fluid h-100 g-0 d-flex flex-column">
        <div class="row g-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                 <a class="navbar-brand" href="/" style="padding-left: 8px;">Wineata</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                      <li class="nav-item">
                        <a class="nav-link{% block active_wineata %}"{% endblock %} href="/wineata">{{ _('Wine atlas') }}</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link{% block active_wineries %}"{% endblock %} href="/wineries">{{ _('Wineries') }}</a>
                      </li>
                      <li class="nav-item{% block active_shop %}"{% endblock %}>
                        <a class="nav-link disabled">{{ _('Shop') }}</a>
                      </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{% if CURRENT_LANGUAGE == 'en' %}<img class="icon-margin" src="{{ url_for('static', filename='icons/united-kingdom.png') }}"  width="20" height="20"> English{% else %}<img class="icon-margin" src="{{ url_for('static', filename='icons/croatia.png') }}"  width="20" height="20"> Hrvatski{% endif %}</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          {% for language in AVAILABLE_LANGUAGES.items() %}
                            {% if CURRENT_LANGUAGE == language[0] %}
                            {% else %}
                              {% if CURRENT_LANGUAGE == 'en' %}
                                <a href="{{ url_for('views.set_language', language=language[0]) }}" class="dropdown-item"><img class="icon-margin" src="{{ url_for('static', filename='icons/croatia.png') }}"  width="20" height="20">{{ language[1] }}</a>
                              {% else %}
                                <a href="{{ url_for('views.set_language', language=language[0]) }}" class="dropdown-item"><img class="icon-margin" src="{{ url_for('static', filename='icons/united-kingdom.png') }}"  width="20" height="20">{{ language[1] }}</a>
                              {% endif %}
                            {%  endif %}
                          {% endfor %}
                        </ul>
                      </li>
                        <li class="nav-item">
                          <a class="nav-link{% block active_login %}"{% endblock %} href="/login">{{ _('Login') }}</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link{% block active_register %}"{% endblock %} href="/register">{{ _('Register') }}</a>
                        </li>
                      </ul>
                  </div>
                </div>
              </nav>
        </div>
        <div class="row g-0 flex-grow-1">{% block content %}{% endblock %}</div>
        <footer class="bg-dark text-center text-secondary"> © 2022 Copyright: Wineata</footer>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body></html>

website/templates/index.html
{% extends "base.html" %}
{% block title %}Wineata{% endblock %}
{% block content %}
Index
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Wineata - {{_('Login')}}{% endblock %}
{% block active_login %} active" aria-current="page"{% endblock %}
{% block content %}
<div class="col-4"></div>
<div class="col-4">
    <form style="padding-top: 20px;">
        <h3 class="d-flex justify-content-center">{{_('Login into account')}}</h3>
        <div class="mb-3">
          <label for="email" class="form-label">{{_('Email address')}}</label>
          <input type="email" class="form-control" id="email" placeholder="{{_('E.g. john.smith@email.com')}}">
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">{{_('Password')}}</label>
          <input type="password" class="form-control" id="password">
          <div id="email" class="form-text"><a href="#" class="link-secondary">{{_('Forgot your password?')}}</a></div>
        </div>
        <button type="submit" class="btn btn-primary">{{_('Login')}}</button>
      </form>
</div>
{% endblock %}

website/templates/register.html
{% extends "base.html" %}
{% block title %}Wineata - {{_('Registration')}}{% endblock %}
{% block active_register %} active" aria-current="page"{% endblock %}
{% block content %}
<div class="col-4"></div>
<div class="col-4">
    <form style="padding-top: 20px;">
        <h3 class="d-flex justify-content-center">{{_('Create new account')}}</h3>
        <div class="mb-3">
            <label for="firstName" class="form-label">{{_('First name')}}</label>
            <input type="text" class="form-control" id="firstName" placeholder="{{_('E.g. John')}}">
        </div>
        <div class="mb-3">
            <label for="lastName" class="form-label">{{_('Last name')}}</label>
            <input type="text" class="form-control" id="lastName" placeholder="{{_('E.g. Smith')}}">
        </div>
        <div class="mb-3">
          <label for="email" class="form-label">{{_('Email address')}}</label>
          <input type="email" class="form-control" id="email" placeholder="{{_('E.g. john.smith@email.com')}}">
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">{{_('Password')}}</label>
          <input type="password" class="form-control" id="password">
        </div>
        <div class="mb-3">
            <label for="repeatPassword" class="form-label">{{_('Repeat Password')}}</label>
            <input type="password" class="form-control" id="repeatPassword">
          </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">{{_('Check me out')}}</label>
        </div>
        <button type="submit" class="btn btn-primary">{{_('Submit')}}</button>
      </form>
</div>
{% endblock %}

website/templates/wineata.html
{% extends "base.html" %}
{% block title %}Wineata - {{_('Wine atlas')}}{% endblock %}
{% block active_wineata %} active" aria-current="page"{% endblock %}
{% block content %}
<div class="col">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2917597.515421893!2d14.163728699988782!3d44.42872465157393!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x133441080add95ed%3A0xa0f3c024e1661b7f!2sCroatia!5e0!3m2!1sen!2shr!4v1647445677356!5m2!1sen!2shr" height="100%" width="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
{% endblock %}

website/templates/wineries.html
{% extends "base.html" %}
{% block title %}Wineata - {{_('Wineries')}}{% endblock %}
{% block active_wineries %} active" aria-current="page"{% endblock %}
{% block content %}
Wineries
{% endblock %}